theme: jekyll-theme-slate
title: Mikhail Kolchar
description: Data Analytics · BI · Data Engineering

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: About me (EN)
    url: /
  - title: Portfolio Data Analytics (EN)
    url: /portfolioDA/
  - title: Portfolio Data Analytics (EN)
    url: /portfolioDS/
  - title: Обо мне (RU)
    url: /about_ru/
  - title: Портфолио Аналитика Данных (RU)
    url: /portfolioDA_ru/    
  - title: Портфолио Дата-сайентиста (RU)
    url: /portfolioDS_ru/  