theme: jekyll-theme-midnight
title: Mikhail Kolchar
description: Data Analytics · BI · Data Engineering

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: Главная
    url: /
  - title: Портфолио
    url: /portfolio/